INSERT INTO account (BALANCE, CURRENCY) VALUES (10.50, 'USD');
INSERT INTO account (BALANCE, CURRENCY) VALUES (250.75, 'EUR');
INSERT INTO account (BALANCE, CURRENCY) VALUES (500.00, 'GBP');
INSERT INTO account (BALANCE, CURRENCY) VALUES (0.00, 'MYR');